#import <React/RCTViewManager.h>

@interface RCT_EXTERN_MODULE(CalendarMonthGridViewManager, RCTViewManager)

RCT_EXPORT_VIEW_PROPERTY(monthDate, NSString)
RCT_EXPORT_VIEW_PROPERTY(selectedDate, NSString)
RCT_EXPORT_VIEW_PROPERTY(dayRecords, NSArray)
RCT_EXPORT_VIEW_PROPERTY(foregroundColorValue, NSString)
RCT_EXPORT_VIEW_PROPERTY(weekdayColorValue, NSString)
RCT_EXPORT_VIEW_PROPERTY(accentColorValue, NSString)
RCT_EXPORT_VIEW_PROPERTY(showsSummary, BOOL)
RCT_EXPORT_VIEW_PROPERTY(summaryRecordedDays, NSNumber)
RCT_EXPORT_VIEW_PROPERTY(summaryTotalDays, NSNumber)
RCT_EXPORT_VIEW_PROPERTY(summaryIndiaDays, NSNumber)
RCT_EXPORT_VIEW_PROPERTY(summaryAbroadDays, NSNumber)
RCT_EXPORT_VIEW_PROPERTY(summaryTravelDays, NSNumber)
RCT_EXPORT_VIEW_PROPERTY(summaryPendingDays, NSNumber)
RCT_EXPORT_VIEW_PROPERTY(summaryCountryText, NSString)
RCT_EXPORT_VIEW_PROPERTY(summaryStatusText, NSString)
RCT_EXPORT_VIEW_PROPERTY(summaryCardColorValue, NSString)
RCT_EXPORT_VIEW_PROPERTY(summaryInputFillColorValue, NSString)
RCT_EXPORT_VIEW_PROPERTY(summaryInputBorderColorValue, NSString)
RCT_EXPORT_VIEW_PROPERTY(summaryMutedColorValue, NSString)
RCT_EXPORT_VIEW_PROPERTY(onDayPress, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onPreviousMonth, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onNextMonth, RCTBubblingEventBlock)

@end
